import Head from 'next/head'
import React from 'react'

export default function Layout({ title, children }) {
    return (
        <div>
        <Head>
        <title> {title ? title + ' - NextMall' : 'NextMall'} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="felx min-h-screen flex-col justify-between">
            <header>
                <nav className="flex h-12 items-center px-4 justify-between shadow-md bg-slate-200">
                    <Link href="/">
                        <a className="text-lg font-bold">Nextmall</a>
                    </Link>
                    <div>
                        <Link href="/cart">
                            <a className="p-2">Cart</a>
                        </Link>
                        <Link href="/login">
                            <a className="p-2">Login</a>
                        </Link>
                    </div>
                </nav>
            </header>

            <main className="container"> {children} </main>

            <footer className="flex h-10 bg-red-100 justify-center items-center shadow-inner">
                <p> Copyright &copy; 2022 NextMall </p>
            </footer>
        </div>
    </div>
    )
}